feat(husky): adjust pre-commit behaviour, remove lint-staged

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,3 +1,11 @@
 #!/usr/bin/env bash
 
-lint-staged
+npm run lint:check || (
+    echo "Lint check failed. Please run 'npm run lint' to fix the issues."
+    exit 1
+)
+
+npm run format:check || (
+    echo "Format check failed. Please run 'npm run format' to fix the issues."
+    exit 1
+)
